### ISSUE TITLE
> generate-scripts.py problem

### ISSUE THREAD

**Issue by dig-lett** [pulp-platform/pulpino#346]
> IPs updated successfully!
> Branch 'verilator' set up to track remote branch 'verilator' from 'origin'.
> Switched to a new branch 'verilator'
> Traceback (most recent call last):
> File "./generate-scripts.py", line 46, in 
> ipdb.export_vsim(script_path="vsim/vcompile/ips", target_tech='umc65')
> AttributeError: 'IPDatabase' object has no attribute 'export_vsim'

You should remove the `ipstools` (which will now be pointing at a much more recent version than what works with PULPino) and `git pull` in the PULPino root before using `update-ips` again.

_Originally posted by @FrancescoConti in https://github.com/pulp-platform/pulpino/issues/304#issuecomment-496859683_

**Comment by dig-lett** [comment]
root@digvijay-X556UQK:/pulpino# sudo python ./generate-scripts.py error: Your local changes to the following files would be overwritten by checkout:
	ipstools/IPDatabase.py
Please, commit your changes or stash them before you can switch branches.
Aborting
Traceback (most recent call last):
  File "./generate-scripts.py", line 46, in <module>
    ipdb.export_vsim(script_path="vsim/vcompile/ips", target_tech='umc65')
AttributeError: 'IPDatabase' object has no attribute 'export_vsim'


I was able to run ./update-ips.py and now, I am having trouble in running ./generate-scripts.py.

Can you please explain the above steps as suggested by you here:
"You should remove the ipstools (which will now be pointing at a much more recent version than what works with PULPino) and git pull in the PULPino root before using update-ips again."
